version: '3.9'

services:
  java_app:
    container_name: java_app
    image: tonnyseko/java_app:1.0.0
    build: .
    ports:
      - 3080:3080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - crud_db
  crud_db:
    container_name: crud_db
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
